import type { NextPage } from 'next';
import Head from 'next/head';
import ExpensesChart from '../components/ExpensesChart';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Expenses chart component | frontendmentor.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <main className="flex items-center justify-center min-h-screen bg-app-sand">
        <ExpensesChart />
      </main>
    </div>
  );
};

export default Home;
